### ISSUE TITLE
 Problem with CEI-API + App Engine of Google Cloud

### ISSUE THREAD

**Issue by matheusdalzot** [barbosagabriel/cei-api#3]
I deployed the scritp in the Google Cloud AppEngine as you mentioned that you also did, but I'm having problems running it in the Browser or Insomnia.
The / token function works perfectly.

When I try to perform the functions:
/wallet 
/transactions
/dividends

When I run on my machine locally it works perfectly.
But in the browser I get this message:

> Error: Server Error
> The server encountered an error and could not complete your request.
> Please try again in 30 seconds.

And I get the following error in the App Engine logs:

> I 2020-08-05T20:33:01.888646Z GET 200 259 B 5,8 s Chrome 84 / GET 200 259 B 5,8 s Chrome 84 5f2b177d00ff0d8f461f573e960001697e6170692d353030393038373230363537343335313930362d3636363731390001323032303038303574313731383037000100
> W 2020-08-05T20:33:11.340270Z GET 500 0 B 9,2 s Chrome 84 /wallet GET 500 0 B 9,2 s Chrome 84 5f2b178700ff05312ef63d0b720001697e6170692d353030393038373230363537343335313930362d3636363731390001323032303038303574313731383037000100
> A 2020-08-05T20:33:11.394451Z Searching wallet - Current date 
> A 2020-08-05T20:33:15.879413Z Logging at CEI... 
> A 2020-08-05T20:33:17.379446Z Error: Error: Protocol error (Target.createTarget): Target closed. 
> A 2020-08-05T20:33:17.379467Z     at /workspace/node_modules/cei-crawler/node_modules/puppeteer/lib/Connection.js:74:56 
> A 2020-08-05T20:33:17.379477Z     at new Promise (<anonymous>) 
> A 2020-08-05T20:33:17.379487Z     at Connection.send (/workspace/node_modules/cei-crawler/node_modules/puppeteer/lib/Connection.js:73:12) 
> A 2020-08-05T20:33:17.379496Z     at Browser._createPageInContext (/workspace/node_modules/cei-crawler/node_modules/puppeteer/lib/Browser.js:174:47) 
> A 2020-08-05T20:33:17.379505Z     at BrowserContext.newPage (/workspace/node_modules/cei-crawler/node_modules/puppeteer/lib/Browser.js:367:26) 
> A 2020-08-05T20:33:17.379512Z     at Browser.newPage (/workspace/node_modules/cei-crawler/node_modules/puppeteer/lib/Browser.js:166:33) 
> A 2020-08-05T20:33:17.379520Z     at Browser.<anonymous> (/workspace/node_modules/cei-crawler/node_modules/puppeteer/lib/helper.js:112:23) 
> A 2020-08-05T20:33:17.379528Z     at CeiCrawler._callee2$ (/workspace/node_modules/cei-crawler/app.js:547:38) 
> A 2020-08-05T20:33:17.379536Z     at tryCatch (/workspace/node_modules/regenerator-runtime/runtime.js:63:40) 
> A 2020-08-05T20:33:17.379554Z     at Generator.invoke [as _invoke] (/workspace/node_modules/regenerator-runtime/runtime.js:293:22) 
> A 2020-08-05T20:33:17.379565Z   -- ASYNC -- 
> A 2020-08-05T20:33:17.379573Z     at Browser.<anonymous> (/workspace/node_modules/cei-crawler/node_modules/puppeteer/lib/helper.js:111:15) 
> A 2020-08-05T20:33:17.379580Z     at CeiCrawler._callee2$ (/workspace/node_modules/cei-crawler/app.js:547:38) 
> A 2020-08-05T20:33:17.379589Z     at tryCatch (/workspace/node_modules/regenerator-runtime/runtime.js:63:40) 
> A 2020-08-05T20:33:17.379605Z     at Generator.invoke [as _invoke] (/workspace/node_modules/regenerator-runtime/runtime.js:293:22) 
> A 2020-08-05T20:33:17.379615Z     at Generator.next (/workspace/node_modules/regenerator-runtime/runtime.js:118:21) 
> A 2020-08-05T20:33:17.379627Z     at asyncGeneratorStep (/workspace/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24) 
> A 2020-08-05T20:33:17.379641Z     at _next (/workspace/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9) 
> A 2020-08-05T20:33:17.379652Z     at processTicksAndRejections (internal/process/task_queues.js:97:5) 

Please help-me, thankyou.

**Comment by barbosagabriel** [comment]
Hi Matheus.

I noticed that the error starts after the crawler process started. It seems like an issue with the puppeteer library, used by the crawler. With that, it is out of the API scope.
I'd suggest you open an issue at the ([cei-crawler repository](https://github.com/Menighin/cei-crawler)) where he can help you better.

**Comment by matheusdalzot** [comment]
Hi Bruno, okay, but did your API work well when you deployed to AppEngine?
Didn't you have any problems with that?
Because I'm using the same version that you made available hehe

**Comment by matheusdalzot** [comment]
I solved after add this code in app.yaml there

> basic_scaling:
> max_instances: 20
> idle_timeout: 5m

**Comment by barbosagabriel** [comment]
Sorry, but I haven’t deployed it on AppEngine. I tried to do that on Heroku, but there was a issue regarding a default timeout.

Glad to hear that you could fix it.
